services:
  frontend:
    build: .
    container_name: sisomapt-web
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      INTERNAL_API_URL: http://host.docker.internal:3001
