version: "2.2"
services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:3010/api"
        INTERNAL_API_URL: "http://host.docker.internal:3010/api"
    container_name: sisom-frontend
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3010/api
      - INTERNAL_API_URL=http://host.docker.internal:3010/api
    restart: unless-stopped
