version: "2.2"
services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: "https://line-sisom.washqueue.com/api"
        INTERNAL_API_URL: "https://line-sisom.washqueue.com/api"
    container_name: sisom-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://line-sisom.washqueue.com/api
      - INTERNAL_API_URL=https://line-sisom.washqueue.com/api
    restart: unless-stopped
